apiVersion: apps/v1 
kind: Deployment
metadata:
  name: free5gc-webui-deployment
spec:
  selector:
    matchLabels:
      app: free5gc-webui
  replicas: 1
  template:
    metadata:
      labels:
        app: free5gc-webui
    spec:
      containers:      
      - name: free5gc-webui-container
        image: registry.gitlab.com/infinitydon/registry/free5gc-webui:v3.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: webuicfg
          mountPath: /go/src/free5gc/config/udrcfg.conf
          subPath: udrcfg.conf
        - name: free5gc
          mountPath: /go/src/free5gc/config/free5GC.conf
          subPath: free5GC.conf
      volumes:
      - name: webuicfg
        configMap:
          name: free5gc-configmap
          items: 
          - key: udrcfg.conf
            path: udrcfg.conf
      - name: free5gc
        configMap:
          name: free5gc-configmap
          items: 
          - key: free5GC.conf
            path: free5GC.conf
---
kind: Service
apiVersion: v1
metadata:
  name: free5gc-webui-service
spec:
  selector:
    app: free5gc-webui
  ports:
  - protocol: TCP
    port: 5000            